Fix build-essential validation function

diff --git a/run_once_install-packages.sh.tmpl b/run_once_install-packages.sh.tmpl
--- a/run_once_install-packages.sh.tmpl
+++ b/run_once_install-packages.sh.tmpl
@@ -39,10 +39,14 @@ install_packages() {
 {{ if eq .chezmoi.os "linux" -}}
 check_build_essential() {
     apt-cache policy build-essential | egrep -i 'installed: [0-9]+?(\.[0-9]+)' > /dev/null 2>&1
+    if [ $? -ne 0 ]; then
+        echo "build-essential is required."
+        exit 1
+    fi
 }
 
 install_deps() {
-    check_cmd_and_fail check_build_essential
+    check_build_essential
     . ~/.local/share/chezmoi/install_packages/linux.sh
     check_cmd brew
     if [ $? -ne 0 ]; then
